# -*- coding: utf-8 -*-
"""ענן - תרגול1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bq5qPgjbTATF0hMd662aoteshiGDQzOB
"""

import ipywidgets as widgets
from IPython.display import display

def build_student_selection_form(file_path):
    """Builds a form with a selection box for students, a textbox for favorite program,
    and a button to update the student's information in the text file.

    Args:
        file_path: Path to the text file containing student data.

    Returns:
        A VBox widget containing the dropdown, textbox, and button.
    """

    try:
        with open(file_path, 'r') as f:
            student_data = f.readlines()
            student_details = {}
            for line in student_data:
                line = line.strip()
                if line:
                    parts = line.split(',')
                    if len(parts) >= 2:
                        student_name = parts[0].strip()
                        details = ', '.join(parts[1:]).strip()
                        student_details[student_name] = details
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return None

    dropdown = widgets.Dropdown(
        options=list(student_details.keys()),
        description='Select a Student:',
    )

    program_textbox = widgets.Text(
        description='Favorite Program:',
        disabled=True  # Disabled initially until a student is selected
    )

    update_button = widgets.Button(
        description='Update Program'
    )
    update_button.disabled = True # Disabled initially until a student is selected

    def on_student_selected(change):
        selected_student = change.new
        if selected_student in student_details:
            program_textbox.disabled = False
            update_button.disabled = False
            print(f"Details for {selected_student}: {student_details[selected_student]}")
        else:
            program_textbox.disabled = True
            update_button.disabled = True
            program_textbox.value = '' # Clear the textbox if no student is selected

    def on_update_button_clicked(b):
        selected_student = dropdown.value
        favorite_program = program_textbox.value.strip()
        if selected_student and favorite_program:
            with open(file_path, 'a') as f:
                f.write(f"\n{selected_student}, {student_details[selected_student]}, {favorite_program}")
            print(f"Program '{favorite_program}' added for {selected_student}")
            # Optionally, you can update the displayed details as well
            student_details[selected_student] = f"{student_details[selected_student]}, {favorite_program}"

    dropdown.observe(on_student_selected, names='value')
    update_button.on_click(on_update_button_clicked)

    form = widgets.VBox([dropdown, program_textbox, update_button])
    return form

# Assuming students.txt is in the current directory
student_form = build_student_selection_form('students.txt')

if student_form:
    display(student_form)

