# -*- coding: utf-8 -*-
"""cloud2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h83O4UUtHp_tmUjtQhrJXw54ArayfGzx
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display
import json

with open("students.json", "r") as f:
    data = json.load(f)
dd = widgets.Dropdown(options=[f"{x['f_name']} {x['l_name']}" for x in data])
display(dd)

student = list(filter(lambda x:f"{x['f_name']} {x['l_name']}"==dd.value,data))[0]

f_name = widgets.Text(value=student['f_name'],placeholder='First Name')
l_name = widgets.Text(value=student['l_name'],placeholder='Last Name')
email = widgets.Text(value=student['mail'],placeholder='Email')
course_list = widgets.Text(value=", ".join(student['courses']),placeholder='web, cloud, ...')
interesting_link = widgets.Text(value=student['link'],placeholder='https://www.youtube.com/watch?v=dQw4w9WgXcQ')
favorite_program = widgets.Text(placeholder="favorite program",value=student.get("program",None))
save = widgets.Button(description='Save')
display(f_name,l_name,email,course_list,interesting_link,widgets.HBox([favorite_program,save]))

def func(b):
    student['program'] = favorite_program.value
    with open("students.json", "w") as f:
        json.dump(data, f)
save.on_click(func)

student



"""```json
[{"f_name": "Peleg", "l_name": "Canfi", "mail": "peleg.canfi@e.braude.ac.il", "courses": ["Web Development", "Cloud Computing", "compilation"], "link": "https://m.media-amazon.com/images/I/31dke4F+cTL._AC_UF894,1000_QL80_.jpg"}, {"f_name": "Reuven", "l_name": "Itzhakov", "mail": "reuven.itzhakov@e.braude.ac.il", "courses": ["Web Development", "Cloud Computing", "compilation"], "link": "https://m.media-amazon.com/images/I/31dke4F+cTL._AC_UF894,1000_QL80_.jpg"}, {"f_name": "Galmo", "l_name": "Linda", "mail": "Galmo.Linda@e.braude.ac.il", "courses": ["Web Development", "Cloud Computing", "compilation"], "link": "https://m.media-amazon.com/images/I/31dke4F+cTL._AC_UF894,1000_QL80_.jpg"}, {"f_name": "Eden", "l_name": "Furmam", "mail": "Eden.Furmam@e.braude.ac.il", "courses": ["Web Development", "Cloud Computing", "compilation"], "link": "https://m.media-amazon.com/images/I/31dke4F+cTL._AC_UF894,1000_QL80_.jpg"}]

```
"""

